name: Main

on:
  push:
    branches:
      - develop
      - master
  pull_request_target:

jobs:
  main:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        dotnet: ['7.0.x', '8.0.x']
    
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}

      - name: Build
        working-directory: src/Blorc.OpenIdConnect
        run: |
          dotnet build

      - name: Test
        working-directory: src/Blorc.OpenIdConnect.Tests
        run: |
          dotnet test
